// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankMyBeerInfrastructure.Context;

#nullable disable

namespace RankMyBeer.Infrastructure.Migrations
{
    [DbContext(typeof(RankMyBeerContext))]
    [Migration("20230822200922_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RankMyBeerDomain.Entities.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Opinion")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("RankMyBeerDomain.Entities.BeerPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.ToTable("BeerPhoto");
                });

            modelBuilder.Entity("RankMyBeerDomain.Entities.BeerPhoto", b =>
                {
                    b.HasOne("RankMyBeerDomain.Entities.Beer", "Beer")
                        .WithMany("BeerPhotos")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");
                });

            modelBuilder.Entity("RankMyBeerDomain.Entities.Beer", b =>
                {
                    b.Navigation("BeerPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
